### ISSUE TITLE
About the local Enforced Look Up Module

### ISSUE THREAD

**Issue by LilRedWu** [Pointcept/OpenIns3D#10]
Thank you for the excellent and insightful work! The paper introduces the Local Enforced Look Up Module, which enhances the proposed mask by calculating the occlusion rate to refine the mask further before passing it to a 2D detector for reclassification. However, I was unable to locate this module in the code, specifically within the pcd2img_point_occlusion_aware function. It's possible I might have missed it. Could you please help me identify which lines of code correspond to the LEL Module?
![image](https://github.com/Pointcept/OpenIns3D/assets/92014745/8b62e582-f5f5-4f4e-a610-396aa470338b)

**Comment by ZheningHuang** [comment]
Hi,

Thank you for your interest in our work and for testing out the code.

Regarding the LEL module, it yields an improvement in final performance; however, it significantly extends the inference time as it requires multiple inferences on each mask. Due to these limitations, we decided not to release the code for this module.

However, if you are interested, I would be more than happy to share the code with you. Could you please let me know your specific usage or interest in that part of the code so I can arrange it accordingly?

Best,
Zhening

**Comment by ZheningHuang** [comment]
It has been a while, but hopefully, this will still be useful. I presented a demo in

[snap_explore.ipynb](https://github.com/Pointcept/OpenIns3D/blob/main/openins3d/trival/snap_explore.ipynb)

which showcases how this is conducted. Let me know if you have more questions

Best,
Zhening
