### ISSUE TITLE
Reproducing results on ScanNet200

### ISSUE THREAD

**Issue by oliviermoliner** [Pointcept/OpenIns3D#26]
Thank you for your interesting work!
Could you please provide instructions for reproducing your results on ScanNet200?
Thank you in advance!

**Comment by ZheningHuang** [comment]
Hi,

We haven’t conducted extensive optimization and testing on ScanNet200, as we found that the results for small objects using the snap-based method didn’t meet our expectations, as noted in the paper. 

However, we did test by replacing snap with RGB images, and the results are included in the paper, as shown below:

<img width="884" alt="image" src="https://github.com/user-attachments/assets/b392a2f3-9f36-42cc-a70f-49222e9096b0">

In any case, you can reproduce it by replacing text_categories in ScanNet setting with ScanNet200 and changing gt_mask to ScanNet200.  gt_mask can obtained by following the preprocessing of mask3d.

Hope this is helpful.

**Comment by LifeBeyondExpectations** [comment]
Did you use all `scannet200` labels for evaluation?

For `scannet`, I found that you use partial labels and exclude some categories, such as `wall` or `floor`.
https://github.com/Pointcept/OpenIns3D/blob/56ccc220dc003e38c644116d7d2078057b6136ad/openins3d/utils.py#L24-L32

**Comment by ZheningHuang** [comment]
Hi,

For Instance Segmentation on ScanNet, wall or floor categories are always excluded. This is also the case for Scannet200.

**Comment by oliviermoliner** [comment]
Hi,

Thank you for your reply! I have now generated the gt_masks for ScanNet200 using the preprocessing of Mask3D.
I tested using Snap and ODISE, which, as far as I understand, should correspond to the last row in Table 11 (is it correct?), but the results I obtain are much lower:

```
################################################################
what           :             AP         AP_50%         AP_25%
################################################################
...
...
----------------------------------------------------------------
average        :          0.032          0.048          0.054
```

Regarding evaluation with RGB-D images instead of Snap, I have a few questions:
- How many RGB-D images per scene did you select?
- How did you select the images?
- How did you preprocess the images (crop, resize, ...)?

**Comment by ZheningHuang** [comment]
Hi,

> How many RGB-D images per scene did you select?

selecting every 20th frame from the raw images

> How did you select the images?

selecting every 20th frame from the raw images, no other selection is applied.

> How did you preprocess the images (crop, resize, etc.)?

only resize to match the size of depth

Just download the scannet dataset with skip=20 and put them into the structure similar to replica, and you will be able to reproduce the results. we reproduce the results with `scannet200 + raw RGB images + Yoloworld `just before releasing the code, so no problem should be expected.  If you can wait until after the CVPR deadline, I can also release that part of the code to make it easier to use.

For `Scannet200 + Snap + ODISE`:

we did not optimized the code for this setting as we did when experimenting because:

ODISE struggles with predicting large-scale classes, as they tend to converge to a single class when the meanings are simliar. While the results are reasonable, as you might see in your visualization, they don’t align well with the metric used (e.g., chairs are classified as office chairs). To make ODISE perform better, we used a multi-stage testing approach, splitting the 200 labels into several parts and testing each part separately, then combining all the predicted masks before evaluating. This approach introduced a lot of false positives, which helped certain classes but worsened others, overall improving the metric, plus location enforced lookup, we have the results showing on the paper. OpenIns3D (with Snap + ODISE) inherently are not designed to perform with very low-quality reconstruction scenes that have a high demand for ambiguous class differentiation as described in the paper, so many tricks were used to enhance the results.

In other experiments, we tested `OpenIns3D with RGB-D and YOLOworld` it works well without any twists.

Best,
Zhening

**Comment by oliviermoliner** [comment]
Thank you very much for your prompt reply!
I prepared the dataset according to your instructions and could reproduce your results:

```
################################################################
what           :             AP         AP_50%         AP_25%
################################################################
...
----------------------------------------------------------------
average        :          0.155          0.201          0.229
```
 (I took 150 frames per scene instead of every 20th which might account for the very slight difference).

Good luck with CVPR!

**Comment by LifeBeyondExpectations** [comment]
Hi,

Regarding your comment,
_"
For `Scannet200 + Snap + ODISE`:
... To make ODISE perform better, we used a multi-stage testing approach, splitting the 200 labels into several parts and testing each part separately, then combining all the predicted masks before evaluating. ...
"_

May I ask the subset of these labels? I am also trying to reproduce the performance and check the inference latency. If you are quite busy with CVPR, just let me know the number of subsets then, I can at least guess the inference latency.

**Comment by ZheningHuang** [comment]
Hi, I remember we divided the 200-category group into five or ten subsets for testing.
